### ISSUE TITLE
Failed to start tor.service: Unit tor.service not found.

### ISSUE THREAD

**Issue by Andr3ix** [FDX100/GOD-KILLER#13]

**Comment by megalopsatlanticus** [comment]
Error removed if Tor is installed and connected. At least for me.

**Comment by Andr3ix** [comment]
I have installed and the message keeps getting

**Comment by megalopsatlanticus** [comment]
Huh. Weird. Every time I launch from Terminal, admin requires PW to launch TOR session, then it works just fine. Sorry...wish I had more for you.

**Comment by FDX100** [comment]
before running the script type **systemctl start tor ** 
then run the script

**Comment by megalopsatlanticus** [comment]
@Andr3ix There ya go. Cheers @FDX100.

**Comment by Andr3ix** [comment]
I get the message as soon as I put the command although it does not affect anything I think the repository works.
