### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by hackw1002** [FDX100/GOD-KILLER#8]
raceback (most recent call last):
  File "install.py", line 2, in <module>
    choice = raw_input('to install press (Y) to uninstall press (N) >> ')
NameError: name 'raw_input' is not defined

**Comment by FDX100** [comment]
Back then (1y ago) i made it for python2

You can run it with python 2
```
python2 install.py
```
If you do not have python2 just directly do these steps
```
sudo chmod +x GOD-KILLER
sudo GOD-KILLER
```
